combine_control_expr = false
condense_wildcard_suffixes = true
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_strings = true
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
tab_spaces = 4
unstable_features = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
